import type { Puzzle } from "@/lib/nonogram";

export const BUILTINS: Puzzle[] = [
  {
    id: "sprout",
    name: "Sprout",
    size: 5,
    rows: ["..#..", "..#..", "#.#.#", ".###.", "..#.."],
  },
  {
    id: "diamond",
    name: "Diamond",
    size: 5,
    rows: ["..#..", ".###.", "#####", ".###.", "..#.."],
  },
  {
    id: "toadstool",
    name: "Toadstool",
    size: 10,
    rows: [
      "...####...",
      ".########.",
      "##########",
      "##########",
      ".########.",
      "...####...",
      "....##....",
      "....##....",
      "...####...",
      "..######..",
    ],
  },
  {
    id: "heart",
    name: "Heart",
    size: 10,
    rows: [
      ".##....##.",
      "##########",
      "##########",
      "##########",
      ".########.",
      "..######..",
      "...####...",
      "....##....",
      "..........",
      "..........",
    ],
  },
  {
    id: "cottage",
    name: "Cottage",
    size: 10,
    rows: [
      "....#.....",
      "...###....",
      "..#####...",
      ".#######..",
      "#########.",
      ".#######..",
      ".#.....#..",
      ".#.###.#..",
      ".#.###.#..",
      ".#.###.#..",
    ],
  },
  // Task 4: redesigned for visual clarity (unique + line-solvable, verified)
  {
    id: "snail",
    name: "Snail",
    size: 5,
    // Shell spiral: outer oval with gap representing spiral interior
    rows: [".###.", "##..#", "#.###", "##..#", ".###."],
  },
  {
    id: "acorn",
    name: "Acorn",
    size: 5,
    // Wide flat cap (row of 5), round body, narrow stem
    rows: ["#####", ".###.", ".###.", "..#..", "..#.."],
  },
  {
    id: "bee",
    name: "Bee",
    size: 5,
    rows: [".#.#.", "#####", ".###.", "..#..", ".#.#."],
  },
  {
    id: "fish",
    name: "Fish",
    size: 5,
    rows: ["....#", ".####", "#####", ".####", "....#"],
  },
  {
    id: "star",
    name: "Star",
    size: 5,
    // Top point, wide arm band, two side + two bottom corner points
    rows: ["..#..", "#####", ".###.", "#.#.#", "#...#"],
  },
  {
    id: "cup",
    name: "Cup",
    size: 5,
    // U-shape walls + solid bottom + narrower footing
    rows: ["#...#", "#...#", "#...#", "#####", ".###."],
  },
  {
    id: "moon",
    name: "Moon",
    size: 5,
    rows: [".###.", "####.", "####.", "####.", ".###."],
  },
  {
    id: "key",
    name: "Key",
    size: 5,
    rows: ["..###", ".#...", "..###", "...#.", "...#."],
  },
  {
    id: "flower",
    name: "Flower",
    size: 10,
    // Cross-shaped petals (N/S/E/W) around filled center — clear petal silhouette
    rows: [
      "....##....",
      "...####...",
      "..######..",
      ".##.##.##.",
      "##.####.##",
      "##.####.##",
      ".##.##.##.",
      "..######..",
      "...####...",
      "....##....",
    ],
  },
  {
    id: "owl",
    name: "Owl",
    size: 10,
    rows: [
      "..######..",
      ".########.",
      "##.####.##",
      "##.####.##",
      ".########.",
      "..######..",
      "...####...",
      "..######..",
      "..#....#..",
      "..#....#..",
    ],
  },
  {
    id: "teapot",
    name: "Teapot",
    size: 10,
    // Lid knob top-center, spout on left (open cavity rows 3-6), handle nubs on right
    rows: [
      "....##....",
      "..######..",
      ".########.",
      "#.######.#",
      "#.######..",
      "#.######..",
      "#.######.#",
      ".########.",
      "..######..",
      "...######.",
    ],
  },
];
